apiVersion: apps/v1
kind: Deployment
metadata:
  name: heh-flask
  labels:
    app: heh-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heh-flask
  template:
    metadata:
      labels:
        app: heh-flask
    spec:
      containers:
        - name: heh-flask
          image: shiroiryu/heh-flask:0533d5059fada5cb91fc36ce580dc5e8bfa43412
          imagePullPolicy: IfNotPresent


