apiVersion: apps/v1
kind: Deployment
metadata:
  name: heh-flask
  labels:
    app: heh-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heh-flask
  template:
    metadata:
      labels:
        app: heh-flask
    spec:
      containers:
        - name: heh-flask
          image: shiroiryu/heh-flask:570feb383843e7790b54ec55f4b33ca640783840
          imagePullPolicy: IfNotPresent


