apiVersion: apps/v1
kind: Deployment
metadata:
  name: heh-flask
  labels:
    app: heh-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heh-flask
  template:
    metadata:
      labels:
        app: heh-flask
    spec:
      containers:
        - name: heh-flask
          image: shiroiryu/heh-flask:2205a3a4e9dd3d08d28da29dc15a28b2bca858c7
          imagePullPolicy: IfNotPresent


